[package]
name = "subnet-id"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.8.1"
ic-agent = "0.24"
tokio = {version = "1.20.1", features = ["full"]}
